dataconf:
  train_img_dir:   "../data/data_mitea/train/images"
  train_label_dir: "../data/data_mitea/train/labels"

  val_img_dir:     "../data/data_mitea/test/images"
  val_label_dir:   "../data/data_mitea/test/labels"
  
  
hyperparams:
  lr: 0.0001
  batch_size: 1
  epochs: 100
  embed_dim: 4

model_restore:
  ckpt_path: ./lightning_logs/version_122

ddconfig:
  double_z: true
  z_channels: 4
  resolution: [160, 160, 128]
  in_channels: 2
  out_ch: 4 # 1 img + 3 labels
  ch: 32  
  ch_mult: [1, 2, 4, 4]  
  num_res_blocks: 2
  attn_resolutions: []
  dropout: 0.0

lossconfig:
  target: "losses.lpips.LPIPSWithDiscriminator"
  params:
    perceptual_weight: 1
    kl_weight: 1
    nll_mode: sum
    